### ISSUE TITLE
how to run in windows?

### ISSUE THREAD

**Issue by seanp2500** [idc/ps4-experiments-405#1]
how would I run this from windows or with bash in windows?  Any help is appreciated.
![untitled](https://user-images.githubusercontent.com/29522279/34509348-1c00d860-f017-11e7-8c82-3ed217567371.png)

**Comment by 0x20Man** [comment]
Dude, it's explained in the red error message, you need the ps4.h header file to compile it.

You should install a PS4-SDK, there are two, CTurt and ps4dev, this probably use the first one, if you look at the list of repositories, there's a forked ps4-payload-sdk that you probably should clone and build (and export the PS4SDK environment variable with the path to library that's referred on the first line of the Makefile)...

**Comment by seanp2500** [comment]
i  know sorry i had a laugh when i read the output so sorry
